/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mybanksystem;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class transferMoney extends javax.swing.JFrame {

   
    FileReader fr;
    Customer mycustomer;
    ArrayList<Customer> customers;
     Transactions tranScreen;
    public transferMoney(Customer customer, ArrayList<Customer> customers,Transactions aThis) 
    {
        fr = new FileReader();
       this.customers = customers;
        this.mycustomer = customer;
        this.tranScreen = aThis;
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ssnlbl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        amountlbl = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        backTran = new javax.swing.JButton();
        backMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("SSN");

        ssnlbl.setBackground(new java.awt.Color(204, 255, 255));
        ssnlbl.setForeground(new java.awt.Color(0, 0, 153));
        ssnlbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnlblActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("amount");

        amountlbl.setBackground(new java.awt.Color(204, 255, 255));
        amountlbl.setForeground(new java.awt.Color(0, 0, 153));

        confirm.setBackground(new java.awt.Color(204, 255, 255));
        confirm.setForeground(new java.awt.Color(0, 0, 153));
        confirm.setText("confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        backTran.setBackground(new java.awt.Color(204, 255, 255));
        backTran.setForeground(new java.awt.Color(0, 0, 153));
        backTran.setText("back to transaction screen");
        backTran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backTranActionPerformed(evt);
            }
        });

        backMain.setBackground(new java.awt.Color(204, 255, 255));
        backMain.setForeground(new java.awt.Color(0, 0, 153));
        backMain.setText("back to main menu");
        backMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(confirm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backTran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ssnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(amountlbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(confirm)
                .addGap(18, 18, 18)
                .addComponent(backTran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backMain)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMainActionPerformed
        BankMain main = new BankMain();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMainActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
       boolean recieverfound = false;
        for(Customer customer: customers)
      {
          if(ssnlbl.getText().equals(customer.getSsn()))
          {   recieverfound = true;
              int amount = Integer.valueOf(amountlbl.getText());
              Customer reciever = customer;
              if(amount <= mycustomer.getBalance() && amount > 0 && amount <= 5000)
              {
                   reciever.setBalance(reciever.getBalance() + amount);
                  mycustomer.setBalance(mycustomer.getBalance() - amount);
              }
             
              try {
           fr.updateFile(customers);
          } catch (FileNotFoundException ex) {
           Logger.getLogger(depositMoney.class.getName()).log(Level.SEVERE, null, ex);
          }
          }
          
      }
        if(recieverfound == false)
        {
             JOptionPane.showMessageDialog(null,"reciever number is not available" );
        }
        
    }//GEN-LAST:event_confirmActionPerformed

    private void backTranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backTranActionPerformed
     
        tranScreen.setVisible(true);
         this.dispose();
         
        
    }//GEN-LAST:event_backTranActionPerformed

    private void ssnlblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnlblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnlblActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountlbl;
    private javax.swing.JButton backMain;
    private javax.swing.JButton backTran;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField ssnlbl;
    // End of variables declaration//GEN-END:variables
}
